### ISSUE TITLE
 context.document.show is not a function

### ISSUE THREAD

**Issue by Nealyang** [BohemianCoding/developer.sketchapp.com#130]
![image](https://user-images.githubusercontent.com/9313216/33309706-f80ec490-d459-11e7-8db1-147006f7423c.png)
sorry my english is poor,when I study how to development a  sketch plugin ,but this statement has error,Is this a version problem? But I see the official website of the document

**Comment by bomberstudios** [comment]
Is that a cracked version of Sketch?

**Comment by bomberstudios** [comment]
Now, back to your question, you're probably looking for `context.document.showMessage("This is a message")` It should work in Sketch 45.2, but if it doesn't try updating to the latest version (we're on 47.1 now, and about to release Sketch 48)
